apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-php.fullname" . }}
  labels:
    {{- include "nginx-php.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nginx-php.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nginx-php.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: nginx
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nginx-php.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx
          image: "{{ .Values.nginx.repository }}:{{ .Values.nginx.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: shared-data
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      initContainers:
        - name: phpfpm
          image: "{{ .Values.php.repository }}:{{ .Values.php.tag | default .Chart.AppVersion }}"
          restartPolicy: Always
          ports:
             - name: phpfpm
               containerPort: {{ .Values.php.port }}
          volumeMounts:
            - name: shared-data
              mountPath: /var/www/html
            - name: php-index
              mountPath: /var/www/html/index.php
              subPath: index.php
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-php-configmap
        - name: php-index
          configMap:
            name: php-configmap