apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-php.fullname" . }}-nginx
  labels:
    {{- include "nginx-php.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "nginx-php.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
